name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
  
jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run:  msbuild .\Moq.QuickMock.sln -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: Moq.QuickMock.vsix
          path: ..\Source\Moq.QuickMock.Vsix\bin\Release\net472\Moq.QuickMock.vsix
