name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Use the desired .NET 8 version

      - name: get Version from source.extension.vsixmanifest, and append version with run_number
        run: |
          $manifestPath = '${{ github.workspace }}\Source\Moq.QuickMock.Vsix\source.extension.vsixmanifest'
          $manifestXml = [xml](Get-Content $manifestPath -Raw)
          $version = $manifestXml.PackageManifest.Metadata.Identity.Version + "." + ${{ github.run_number }}
          echo "APP_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          $manifestXml.PackageManifest.Metadata.Identity.Version = $version
          $manifestXml.save($manifestPath)
          
      - name: print content of source.extension.vsixmanifest
        run: get-content .\Source\Moq.QuickMock.Vsix\source.extension.vsixmanifest
      
      - name: print APP_VERSION
        run: Write-Host $APP_VERSION

      - name: restore dependencies
        run: dotnet restore
      
      - name: build non-VSIX projects
        run: |
          dotnet build --configuration Release --no-restore \
            ./Source/Moq.QuickMock/Moq.QuickMock.csproj \
            ./Source/Moq.QuickMock.Vsix.Tests/Moq.QuickMock.Vsix.Tests.csproj      
      
      - name: tests
        run: dotnet test ./Source/Moq.QuickMock.Vsix.Tests/Moq.QuickMock.Vsix.Tests.csproj --configuration Release --no-build --verbosity normal   
      
      - name: build VSIX project
        run: msbuild ./Moq.QuickMock.Vsix/Moq.QuickMock.Vsix.csproj /p:Configuration=Release

      # - name: add msbuild to PATH
      #   uses: microsoft/setup-msbuild@v1.1
      
      # - name: setup nuget
      #   uses: nuget/setup-nuget@v2
      #   with:
      #     nuget-version: '6.x'
      
      # - name: nuget restore
      #   run: nuget restore Moq.QuickMock.sln
      
      # - name: build solution
      #   #run:  msbuild .\Moq.QuickMock.sln -t:rebuild -verbosity:diag -property:Configuration=Release
      #   run:  msbuild Moq.QuickMock.sln -t:rebuild -property:Configuration=Release

      - name: rename Moq.QuickMock.Vsix.vsix to Moq.QuickMock.W.X.Y.Z.vsix
        run:  ren ${{ github.workspace }}\Source\Moq.QuickMock.Vsix\bin\Release\net472\Moq.QuickMock.Vsix.vsix Moq.QuickMock.${{ env.APP_VERSION }}.vsix

      - name: create artifact
        uses: actions/upload-artifact@v4
        with:
          name: Moq.QuickMock.${{ env.APP_VERSION }}.vsix
          path: ${{ github.workspace }}\Source\Moq.QuickMock.Vsix\bin\Release\net472\Moq.QuickMock.${{ env.APP_VERSION }}.vsix
