name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: get version from source.extension.vsixmanifest
        run: |
          $manifestPath = '${{ github.workspace }}\Source\Moq.QuickMock.Vsix\source.extension.vsixmanifest'
          $manifestXml = [xml](Get-Content $manifestPath -Raw)
          $version = $manifestXml.PackageManifest.Metadata.Identity.Version + "." + ${{ github.run_number }}
          echo "APP_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: print APP_VERSION
        run: Write-Host $APP_VERSION

      - name: add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: setup nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'
      
      - name: nuget restore
        run: nuget restore Moq.QuickMock.sln
      
      - name: build solution
        #run:  msbuild .\Moq.QuickMock.sln -t:rebuild -verbosity:diag -property:Configuration=Release
        run:  msbuild Moq.QuickMock.sln -t:rebuild -property:Configuration=Release

      - name: rename Moq.QuickMock.Vsix.vsix to Moq.QuickMock.vsix
        run:  ren ${{ github.workspace }}\Source\Moq.QuickMock.Vsix\bin\Release\net472\Moq.QuickMock.Vsix.vsix Moq.QuickMock$APP_VERSION.vsix

      - name: create artifact
        uses: actions/upload-artifact@v3
        with:
          name: Moq.QuickMock.vsix
          path: ${{ github.workspace }}\Source\Moq.QuickMock.Vsix\bin\Release\net472\Moq.QuickMock$APP_VERSION.vsix
